### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Emelmr** [PlutoSolutions/Future#114]
crash in middle of game
[latest.log](https://github.com/PlutoSolutions/Future/files/12672812/latest.log)
[Uploading latest.log…]()
[crash-2023-09-20_20.06.44-client.txt](https://github.com/PlutoSolutions/Future/files/12672818/crash-2023-09-20_20.06.44-client.txt)

**Comment by mr-nv** [comment]
java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.cm

this is a problem with baritone, remove -noverify or -Xverify:none from your java arguments
