### ISSUE TITLE
Getting "Username or password is not matching!" error

### ISSUE THREAD

**Issue by nounoxs** [PlutoSolutions/Future#12]
Error
![image](https://user-images.githubusercontent.com/95464847/209429782-b98a29e3-f14e-4049-bb29-3ef918bcefdd.png)

(The auth_key file in %username%/Future folder)

Libs
![image](https://user-images.githubusercontent.com/95464847/209429816-fda97c3e-4e19-45f1-8129-006629d3a4a5.png)

Log
https://pastebin.com/1JAxG1mt

Launcher: MultiMC | Java: Corretto 8 (1.8.0_352)

**Comment by maywr** [comment]
tweaker should go before futures loader. read the readme first

**Comment by nounoxs** [comment]
> tweaker should go before futures loader. read the readme first

Works! thx
