### ISSUE TITLE
multimc moment

### ISSUE THREAD

**Issue by goztb22** [PlutoSolutions/Future#13]
![image](https://user-images.githubusercontent.com/80268473/209431377-98248d0c-a155-4031-902d-2551a66c3f39.png)

**Comment by goztb22** [comment]
![image](https://user-images.githubusercontent.com/80268473/209431544-b645f4b8-6265-4fa4-9c09-51b1d6084a87.png)
если че вот

**Comment by maywr** [comment]
Играть в автономном режиме.

**Comment by goztb22** [comment]
0x1 -1
🥰

**Comment by goztb22** [comment]
https://paste.ee/p/Cnghp

**Comment by goztb22** [comment]
все работает
