### ISSUE TITLE
пиздец

### ISSUE THREAD

**Issue by goztb22** [PlutoSolutions/Future#14]
![image](https://user-images.githubusercontent.com/80268473/209434296-c55a78a5-b52a-47fb-8c61-b79041698fa5.png)
![image](https://user-images.githubusercontent.com/80268473/209434311-73d1645e-f18b-4e4a-a137-ed5bf6c8a337.png)

**Comment by 0-x-2-2** [comment]
Make sure you are using the recommended Java version and the official Minecraft launcher or MultiMC. Most neo-cracked launchers won't work with the client due to the malware they include with their launchers conflicting or just simply setting up the game classpath incorrectly. Simplistic cracked launchers will work but not many of those exist anymore and have weird features and mods that get injected into the game for skins and other shit.

**Comment by goztb22** [comment]
MultiMC version: 0.7.0


Launched instance in offline mode

Minecraft folder is:
C:/Users/Administrator/Desktop/mmc/instances/1.12.22/.minecraft


Java path is:
C:/Program Files/Amazon Corretto/jre8/bin/javaw.exe


Checking Java version...
Java is version 1.8.0_352, using 64-bit architecture, from Amazon.com Inc..


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Administrator/Desktop/mmc/instances/1.12.22/natives

Libraries:
  C:/Users/Administrator/Desktop/mmc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Administrator/Desktop/mmc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/Administrator/Desktop/mmc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Administrator/Desktop/mmc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Administrator/Desktop/mmc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Administrator/Desktop/mmc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Administrator/Desktop/mmc/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Administrator/Desktop/mmc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Administrator/Desktop/mmc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Administrator/Desktop/mmc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Administrator/Desktop/mmc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/Administrator/Desktop/mmc/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-universal.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/Users/Administrator/Desktop/mmc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Administrator/Desktop/mmc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Administrator/Desktop/mmc/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/Administrator/Desktop/mmc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/Administrator/Desktop/mmc/instances/1.12.22/libraries/tweaker-1.0.jar
  C:/Users/Administrator/Desktop/mmc/instances/1.12.22/libraries/loader-1.0.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/Administrator/Desktop/mmc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Administrator/Desktop/mmc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/Administrator/Desktop/mmc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Params:
  --username  --version 1.12.2 --gameDir C:/Users/Administrator/Desktop/mmc/instances/1.12.22/.minecraft --assetsDir C:/Users/Administrator/Desktop/mmc/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker --tweakClass com.example.tweaker.ILOVEFUTURECLIENT --tweakClass net.futureclient.loader.launch.launchwrapper.LaunchWrapperEntryPoint

Window size: 854 x 480

Java Arguments:
[-javaagent:C:/Users/Administrator/Desktop/mmc/injectors/authlib-injector-1.2.1.jar=ely.by, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4000m, -Xmx6000m, -Duser.language=en]


Minecraft process ID: 2888


[authlib-injector] [INFO] Logging file: C:\Users\Administrator\Desktop\mmc\instances\1.12.22\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.1
[authlib-injector] [INFO] Authentication server: https://ely.by
[authlib-injector] [INFO] Redirect to: https://account.ely.by/api/authlib-injector
[authlib-injector] [INFO] Disabled Mojang namespace
Using onesix launcher.

[14:57:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:57:46] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:57:46] [main/INFO] [LaunchWrapper]: Loading tweak class name com.example.tweaker.ILOVEFUTURECLIENT
loading native
[CREDITS] cracked by github.com/NUMBERONEMINECRAFTFAN & github.com/maywr w/ help from github.com/mr-nv for github.com/PlutoSolutions
Built on: Dec 23 2022
[INFO] loading jvm.dll
[INFO] Found SecureRandom class
[INFO] Found Tweaker class
[INFO] Found transform method
Changing nextBytes
[INFO] Got transformed SecureRandom
[INFO] resolving JVM exports
server
[14:57:47] [main/INFO] [LaunchWrapper]: Loading tweak class name net.futureclient.loader.launch.launchwrapper.LaunchWrapperEntryPoint
[14:57:47] [FutureListener/INFO] [FutureServer]: waiting for connection
Replacing SecureRandom bytes with key 0
Replacing SecureRandom bytes with key 1
Replacing SecureRandom bytes with key 2
Replacing SecureRandom bytes with key 3
Replacing SecureRandom bytes with key 4
Replacing SecureRandom bytes with key 5
Replacing SecureRandom bytes with key 6
Replacing SecureRandom bytes with key 7
Replacing SecureRandom bytes with key 8
Replacing SecureRandom bytes with key 9
[14:57:53] [FutureListener/INFO] [FutureServer]: connection 1 is handled
[14:57:53] [FutureListener/INFO] [FutureServer]: waiting for connection
[14:57:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:57:57] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[14:57:57] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_352, running on Windows 10:amd64:10.0, installed at C:\Program Files\Amazon Corretto\jre8
[14:57:58] [main/INFO] [FML]: Searching C:\Users\Administrator\Desktop\mmc\instances\1.12.22\.minecraft\mods for mods
[14:57:58] [main/INFO] [LaunchWrapper]: Calling tweak class com.example.tweaker.ILOVEFUTURECLIENT
[14:57:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.futureclient.loader.launch.launchwrapper.LaunchWrapperEntryPoint
[14:57:58] [FutureListener/INFO] [FutureServer]: connection 2 is handled
[14:57:58] [FutureListener/INFO] [FutureServer]: waiting for connection
[14:58:00] [main/INFO] [STDOUT]: [java.security.SecureRandom:nextBytes:491]: Replacing SecureRandom bytes with key 10
[14:58:00] [main/INFO] [STDOUT]: [java.security.SecureRandom:nextBytes:491]: Replacing SecureRandom bytes with key 11
[14:58:00] [FutureListener/INFO] [FutureServer]: connection 3 is handled
[14:58:00] [FutureListener/INFO] [FutureServer]: waiting for connection
[14:58:00] [main/INFO] [STDOUT]: [java.security.SecureRandom:nextBytes:491]: Replacing SecureRandom bytes with key 12
[14:58:00] [main/INFO] [STDOUT]: [java.security.SecureRandom:nextBytes:491]: Replacing SecureRandom bytes with key 13
[14:58:00] [main/INFO] [STDOUT]: [java.security.SecureRandom:nextBytes:491]: Replacing SecureRandom bytes with key 14
[INFO] setting hooks
Процесс завершён с кодом 0 (0x0).
Пожалуйста, обратите внимание, что обычно ни кода выхода, ни его описания недостаточно для диагностики проблем!
Всегда загружать весь журнал целиком, а не только код выхода.
Clipboard copy at: 24 Dec 2022 14:58:04 +0300

**Comment by WMSGaming** [comment]
crazy

**Comment by mr-nv** [comment]
![image](https://user-images.githubusercontent.com/31269663/209436808-aa7b4724-06b5-430c-b221-af41f6d644a9.png)
оно ругается из за этой хуйни, если ты играешь на multimc5-cracked или же ultimmc то щас я высру гайд на тл легаси

**Comment by goztb22** [comment]
ок
