### ISSUE TITLE
can you try to get future code?

### ISSUE THREAD

**Issue by neilhuang007** [PlutoSolutions/Future#20]
because after i look at the code of your wonderful installer(actually a creation of genius),i find out that actually we are just applying the auth key into the loader, so can you try to get the real code of future. I think you guys can done it and we will be over of future client maker skidding all over and selling client that is worth nothing for 20 dollars
code for applying auth(to make sure i'm not faking)
`if ( mcProfile.getSelectedItem() == null || mcProfile.getSelectedItem().toString().isEmpty() )
            {
                Utils.showError( "Select the actual profile first", false );
                return;
            }
            File futureDir = new File( System.getProperty( "user.home" ) + "\\Future" );
            futureDir.mkdir();
            File authKey = new File( futureDir, "auth_key" );
            try
            {
                if ( !authKey.exists() && !authKey.createNewFile() ) throw new IOException();
                Files.write( authKey.toPath(), Utils.readAllBytes( Objects.requireNonNull( getClass().getResourceAsStream( "/assets/auth_key" ) ) ) );
                // Utils.showError( Utils.readAllBytes( Objects.requireNonNull( getClass().getResourceAsStream( "/assets/auth_key" ) ) ) , false );
            } catch ( Exception ex )`

**Comment by mr-nv** [comment]
the crack itself is a server emulator for future loader, the tweaker redirects all connections to your own local server that it also creates. auth_key is just needed for the server emulator to work properly
if you know a way you can try getting all future classes so you can deobfuscate and copypaste shit from it later, but we are not gonna do that
