### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MinecraftPlayer222** [PlutoSolutions/Future#23]
It says error u are using unsupported jvm arguments

**Comment by mr-nv** [comment]
what launcher

**Comment by MinecraftPlayer222** [comment]
> what launcher

Sk launcher

**Comment by MinecraftPlayer222** [comment]
> what launcher

Should i use tl legacy?

**Comment by mr-nv** [comment]
idk what that is but yeah use tl legacy

**Comment by mr-nv** [comment]
https://tlaun.ch/jar

**Comment by MinecraftPlayer222** [comment]
> https://tlaun.ch/jar

Thx works perfectly
