### ISSUE TITLE
nothing happens after clicking install

### ISSUE THREAD

**Issue by titaniummachine1** [PlutoSolutions/Future#32]

**Comment by mr-nv** [comment]
https://github.com/PlutoSolutions/Future#tl-legacy
redo each step right from the start, maybe make a vid of how you do it

**Comment by Popx1** [comment]
when i open it whit cmd its send me this 
Exception in thread "main" java.lang.NullPointerException
      at solutions.pluto.Utils.lambda$getMinecraftProfiles
      at java.util.Map.forEach(Map.java:630)
      at solutions.pluto.Utils.getMinecraftProfiles(Utils.
      at solutions.pluto.InstallerFrame.<init>(InstallerFr
      at solutions.pluto.Bootstrap.main(Bootstrap.java:27)

**Comment by mr-nv** [comment]
@maywr ау помогай

**Comment by maywr** [comment]
are you using the official Minecraft Launcher?

**Comment by Popx1** [comment]
no its the installer

**Comment by Popx1** [comment]
help me pls

**Comment by maywr** [comment]
what minecraft launcher you use

**Comment by Popx1** [comment]
the installer dont open not the game

**Comment by maywr** [comment]
PrismLauncher is a fork of MultiMC. you don't need to use the installer for it, please read the readme before making issues

**Comment by maywr** [comment]
it doesn't work on prism launcher. get MuliMC

**Comment by Popx1** [comment]
That worked thanks
