### ISSUE TITLE
It installs optifine even when the option is not turned on

### ISSUE THREAD

**Issue by TOBIBLASTER00912** [PlutoSolutions/Future#33]
I wanted to install future without optifine but it installs anyway.. What can i do? My laptop is not the best and i have 0fps with optifine.. Thanks for reading!

Btw Client is safe!

**Comment by mr-nv** [comment]
how the fuck do you have less fps with optifine????? anyway remove optifine.jar from the mods folder in .minecraft

**Comment by TOBIBLASTER00912** [comment]
Tysm i have low fps because its an old laptop from my grandma lol i buy a gaming laptop in a few months but till then i cant use optifine because only 4gb of ram xD but anyways, thank you!
