### ISSUE TITLE
only works on gaydows

### ISSUE THREAD

**Issue by hexman1337** [PlutoSolutions/Future#35]
fucking gaydows user

**Comment by NUMBERONEMINECRAFTFAN** [comment]
solutions: install windows

**Comment by mr-nv** [comment]
youre calling windows gay but why do faggots, trannies and other mentally ill people choose linux? just something for you to think about

**Comment by hexman1337** [comment]
nigga your OS have rat stupid nigger :joy:

**Comment by hexman1337** [comment]
nigga your OS have rat stupid nigger :joy:

**Comment by hexman1337** [comment]
nigga your OS have rat stupid nigger :joy:

**Comment by NUMBERONEMINECRAFTFAN** [comment]
No sir it does not.

**Comment by mr-nv** [comment]
I Have 360 Total Security Installed So Im Clean Also Reported For Racism
Xir Racism Is Not Tolerated Up In This Bitch So U Better Go Take Down Ur
Comments Right This Instance

сб, 14 янв. 2023 г., 11:55 hexman1337 ***@***.***>:

**Comment by hexman1337** [comment]
stupid Russian

**Comment by hexman1337** [comment]
antivirus ez disable

**Comment by mr-nv** [comment]
wrong
