### ISSUE TITLE
help

### ISSUE THREAD

**Issue by shasdfasdqw** [PlutoSolutions/Future#38]
![image](https://user-images.githubusercontent.com/104833655/211051980-b3baceaf-f322-43a5-b3a9-8f81d657483d.png)

**Comment by shasdfasdqw** [comment]
uh

**Comment by shasdfasdqw** [comment]
I spent 4 hours trying to fix it and i fixed it

**Comment by NUMBERONEMINECRAFTFAN** [comment]
good job
