### ISSUE TITLE
I can't open the installer file

### ISSUE THREAD

**Issue by An040620hihi** [PlutoSolutions/Future#39]
i've got java jdk 8 and pc 64 bit

**Comment by mr-nv** [comment]
Cool

**Comment by An040620hihi** [comment]
what?

**Comment by mr-nv** [comment]
install java properly or install the crack manually without touching the
installer

пн, 23 янв. 2023 г., 04:50 An040620hihi ***@***.***>:

**Comment by mr-nv** [comment]
https://crystalpvp.ru/deadcode/java.php
