### ISSUE TITLE
Rusherhack has been updated Please crack Rusherhack Plus v1.3.1

### ISSUE THREAD

**Issue by typsabo** [PlutoSolutions/Future#40]
Rusherhack has been updated Please crack Rusherhack Plus v1.3.1

**Comment by redvx** [comment]
https://t.me/mayvvr

**Comment by redvx** [comment]
вы можете найти кряк rusherhack здесь

**Comment by NUMBERONEMINECRAFTFAN** [comment]
shut the fuck up nigger

**Comment by mr-nv** [comment]
yeah what she said
