### ISSUE TITLE
Getting "Invalid credentials" error even when auth_key is in Future folder

### ISSUE THREAD

**Issue by Spritzerland** [PlutoSolutions/Future#5]
I'm on a mac

**Comment by Spritzerland** [comment]
Tried to fix the installer, same error

**Comment by Spritzerland** [comment]
https://www.mediafire.com/file/gh6pcrygxr7rpq7/FutureInstaller-mac-broken.jar/file

here's the jar if anyone wants to debug

**Comment by NUMBERONEMINECRAFTFAN** [comment]
doesnt work for mac

**Comment by NUMBERONEMINECRAFTFAN** [comment]
windows x64 only

**Comment by Spritzerland** [comment]
could you edit the loader jar so it points to /Users/<user>/Future/auth_key or is that not possible?
