### ISSUE TITLE
Uh to i use tlauncher and it just wont open

### ISSUE THREAD

**Issue by PyroDoo** [PlutoSolutions/Future#84]
[crash-2023-02-04_11.23.20-server.txt](https://github.com/PlutoSolutions/Future/files/10607866/crash-2023-02-04_11.23.20-server.txt)

**Comment by mr-nv** [comment]
OpenGlRenderer: Intel(R) HD Graphics 2000Bro what is this siht😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂
