### ISSUE TITLE
Can u guys maybe do a flora client crack?

### ISSUE THREAD

**Issue by TOBIBLASTER0912** [PlutoSolutions/Future#85]
flora is a really strong cpvp client so i want it lol
i think flora is easy to crack or maybe you just need to leak the jar idk
but i would be so happy if u make a free flora jar!
<3
ps: love ur cracks they are fire!!

**Comment by mr-nv** [comment]
whats that? no dont answer im not gonna crack that shit

**Comment by TOBIBLASTER0912** [comment]
lol
