### ISSUE TITLE
why cant i run rusher crack with future?

### ISSUE THREAD

**Issue by Knackkk** [PlutoSolutions/Future#93]
It used to work when I deleted my .minecraft folder it deosnt work anymore

**Comment by mr-nv** [comment]
idk it should work perfectly fine

**Comment by Knackkk** [comment]
I can send you the crash log

**Comment by mr-nv** [comment]
ok send it here

вс, 5 мар. 2023 г., 00:30 knack ***@***.***>:

**Comment by Knackkk** [comment]
[crash-2023-03-03_10.25.14-client.txt](https://github.com/PlutoSolutions/Future/files/10889793/crash-2023-03-03_10.25.14-client.txt)

**Comment by mr-nv** [comment]
maywr's crack requires -noverify to be put in java arguments

вс, 5 мар. 2023 г., 01:24 knack ***@***.***>:

**Comment by Knackkk** [comment]
Bruh

**Comment by Knackkk** [comment]
In your opinion what's the best auto crystal
