### ISSUE TITLE
Can't launch future

### ISSUE THREAD

**Issue by 6Mouse** [PlutoSolutions/Future#94]
[latest.log](https://github.com/PlutoSolutions/Future/files/10889322/latest.log)
Tried everything that has been said in the main page. First time I for some reason thought that TL forge would work but it didnt. Then it wasnt compatible with rusher and pyro so i deleted them, then i tried using amazon jdk 8 or whatever to install it and it still didnt work then i tried using java 8 in launcher settings which didnt help anything and now im here. Please help, i attached the latest.log file for you.

**Comment by mr-nv** [comment]
>Tried everything that has been said in the main page
except you didnt
![image](https://user-images.githubusercontent.com/31269663/222928705-72963fdf-d8d5-4dd7-9c43-d45b5b645d47.png)
