### ISSUE TITLE
Client crashes

### ISSUE THREAD

**Issue by MariusLord** [PlutoSolutions/Future#99]
Im using multimc on windows 11 x64 and i tried both temurin java 8 and amazon coretto 8. Followed the instalation procedure, yet nothing worked. Tried on another pc too, just to get the same crash.
Is it a java issue or some sort? The client worked for me before i reinstalled my system.

![image](https://user-images.githubusercontent.com/95578412/226672752-c1494319-0258-44d7-b8c1-b77ba2dd821a.png)

**Comment by mr-nv** [comment]
install visual c++ redistributables
https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/
